const { DataTypes } = require('sequelize')
const sequelize = require('../config')

// Auto-generated by the pricing engine after a service memo is reviewed.
// One invoice per memo (unique on memo_id). Line items are in invoice_line_items.
// xero_invoice_id is populated after a successful Xero push.
const Invoice = sequelize.define('Invoice', {
  id:          { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  memo_id:     { type: DataTypes.INTEGER, allowNull: false, unique: true, references: { model: 'service_memos',     key: 'id' } },
  booking_id:  { type: DataTypes.INTEGER, allowNull: false,              references: { model: 'bookings',          key: 'id' } },
  client_id:   { type: DataTypes.INTEGER, allowNull: false,              references: { model: 'clients',           key: 'id' } },
  // Nullable: an 'unmatched' invoice (no active contract for the client) carries no
  // contract_id. Every priced invoice ('matched' onward) always sets it.
  contract_id: { type: DataTypes.INTEGER, allowNull: true,               references: { model: 'pricing_contracts', key: 'id' } },
  approved_by: { type: DataTypes.INTEGER, allowNull: true,               references: { model: 'users',             key: 'id' } },
  subtotal:      { type: DataTypes.DECIMAL(10, 2), allowNull: false, defaultValue: 0.00 },
  // GST-exclusive pricing: the effective-dated rate is selected when the invoice is
  // generated and copied onto the invoice. The snapshot makes historical invoices
  // immutable when a later GST period is added to gst_rates.
  gst_rate_id:       { type: DataTypes.INTEGER, allowNull: true, references: { model: 'gst_rates', key: 'id' } },
  gst_rate_percent:  { type: DataTypes.DECIMAL(5, 2), allowNull: true },
  gst_effective_date:{ type: DataTypes.DATEONLY, allowNull: true },
  xero_tax_type:     { type: DataTypes.STRING(50), allowNull: true },
  tax_amount:    { type: DataTypes.DECIMAL(10, 2), allowNull: false, defaultValue: 0.00 },
  total_amount:  { type: DataTypes.DECIMAL(10, 2), allowNull: false, defaultValue: 0.00 },
  status: {
    type: DataTypes.ENUM('matched', 'adjusted', 'approved', 'synced_to_xero', 'failed', 'unmatched'),
    allowNull: false,
    defaultValue: 'matched',
  },
  xero_invoice_id: { type: DataTypes.STRING(255), allowNull: true },
  approved_at:     { type: DataTypes.DATE,        allowNull: true },
  // Chargeable items the crew recorded on the memo that the matched contract has no rate
  // for, as [{ surcharge_type, label, detail }]. Written by the pricing engine at approval
  // time and surfaced on the Invoice Detail screen so the AR Specialist can price them by
  // hand instead of the charge silently disappearing. Empty array = nothing was dropped.
  unpriced_surcharges: { type: DataTypes.JSONB, allowNull: false, defaultValue: [] },
  // Closes a revenue-leakage row that will not be recovered. Set together or not at all:
  // NULL across all three means "still open", which is the correct default for every
  // historical row. The actor is stored because this is the one action in the report that
  // decides money will not be collected, and a write-off needs an author.
  //
  // Dismissing does NOT touch unpriced_surcharges - the record of what went unbilled is
  // kept intact, so a dismissed row can still be inspected and the decision reversed.
  leakage_dismissed_at:     { type: DataTypes.DATE,    allowNull: true },
  leakage_dismissed_reason: { type: DataTypes.TEXT,    allowNull: true },
  leakage_dismissed_by:     { type: DataTypes.INTEGER, allowNull: true, references: { model: 'users', key: 'id' } },
}, {
  tableName: 'invoices',
  underscored: true,
})

module.exports = Invoice
