const { DataTypes } = require('sequelize')
const sequelize = require('../config')

// Auto-generated by the pricing engine after a service memo is reviewed.
// One invoice per memo (unique on memo_id). Line items are in invoice_line_items.
// xero_invoice_id is populated after a successful Xero push.
const Invoice = sequelize.define('Invoice', {
  id:          { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  memo_id:     { type: DataTypes.INTEGER, allowNull: false, unique: true, references: { model: 'service_memos',     key: 'id' } },
  booking_id:  { type: DataTypes.INTEGER, allowNull: false,              references: { model: 'bookings',          key: 'id' } },
  client_id:   { type: DataTypes.INTEGER, allowNull: false,              references: { model: 'clients',           key: 'id' } },
  contract_id: { type: DataTypes.INTEGER, allowNull: false,              references: { model: 'pricing_contracts', key: 'id' } },
  approved_by: { type: DataTypes.INTEGER, allowNull: true,               references: { model: 'users',             key: 'id' } },
  subtotal:      { type: DataTypes.DECIMAL(10, 2), allowNull: false, defaultValue: 0.00 },
  tax_amount:    { type: DataTypes.DECIMAL(10, 2), allowNull: false, defaultValue: 0.00 },
  total_amount:  { type: DataTypes.DECIMAL(10, 2), allowNull: false, defaultValue: 0.00 },
  status: {
    type: DataTypes.ENUM('matched', 'adjusted', 'approved', 'synced_to_xero', 'failed', 'unmatched'),
    allowNull: false,
    defaultValue: 'matched',
  },
  xero_invoice_id: { type: DataTypes.STRING(255), allowNull: true },
  approved_at:     { type: DataTypes.DATE,        allowNull: true },
}, {
  tableName: 'invoices',
  underscored: true,
})

module.exports = Invoice
