// Shared intake sample data derived from backend seed-intakes.js.
// This central file prevents hard-coded intake samples from living in page components.
export const INITIAL_INTAKES = [
  {
    ref: 'EFAR-2026-00001',
    submitted: '8 Jul 2026, 09:20 AM',
    name: 'Wei Lin Tan',
    org: 'Tan Tock Seng Hospital',
    email: 'weiling.tan@ttsh.com.sg',
    phone: '64501234',
    serviceType: 'EAS (Emergency Ambulance Services)',
    tier: 'Advanced',
    status: 'Pending',
    preferredDate: '10 Jul 2026',
    preferredTime: '14:00',
    pickup: 'Tan Tock Seng Hospital, Ward 5B, 11 Jalan Tan Tock Seng, Singapore 308433',
    destination: 'National University Hospital, 5 Lower Kent Ridge Road, Singapore 119074',
    notes: 'Patient is on supplemental oxygen. Requires monitoring throughout transfer.',
  },
  {
    ref: 'EFAR-2026-00002',
    submitted: '9 Jul 2026, 02:05 PM',
    name: 'Marcus Lim',
    org: 'ABC Corporation',
    email: 'marcus.lim@abc-corp.com.sg',
    phone: '65432100',
    serviceType: 'Event Standby',
    tier: 'Basic',
    status: 'Pending',
    preferredDate: '15 Aug 2026',
    preferredTime: '08:00',
    pickup: 'ABC Corporation HQ, 10 Anson Road, Singapore 079903',
    destination: 'Nearest A&E (if activated)',
    notes: 'Annual company sports day. Approx 200 participants. Request standby from 0800-1700.',
  },
  {
    ref: 'EFAR-2026-00003',
    submitted: '7 Jun 2026, 04:30 PM',
    name: 'Dr. Priya Nair',
    org: 'Tan Tock Seng Hospital',
    email: 'priya.nair@ttsh.com.sg',
    phone: '64501111',
    serviceType: 'EAS (Emergency Ambulance Services)',
    tier: 'Advanced',
    status: 'Confirmed',
    preferredDate: '10 Jun 2026',
    preferredTime: '09:00',
    pickup: 'Tan Tock Seng Hospital, Ward 5B, 11 Jalan Tan Tock Seng, Singapore 308433',
    destination: 'National University Hospital, 5 Lower Kent Ridge Road, Singapore 119074',
    notes: '',
  },
  {
    ref: 'EFAR-2026-00004',
    submitted: '9 Jun 2026, 08:00 PM',
    name: 'Siti Rahimah',
    org: 'Tan Tock Seng Hospital',
    email: 'siti.r@ttsh.com.sg',
    phone: '64502222',
    serviceType: 'EAS (Emergency Ambulance Services)',
    tier: 'Basic',
    status: 'Confirmed',
    preferredDate: '11 Jun 2026',
    preferredTime: '22:00',
    pickup: 'Tan Tock Seng Hospital, A&E, 11 Jalan Tan Tock Seng, Singapore 308433',
    destination: 'Khoo Teck Puat Hospital, 90 Yishun Central, Singapore 768828',
    notes: 'Patient requiring oxygen support. Floor access at destination.',
  },
  {
    ref: 'EFAR-2026-00005',
    submitted: '11 Jun 2026, 05:00 PM',
    name: 'Ahmad Fauzi',
    org: 'Tan Tock Seng Hospital',
    email: 'ahmad.fauzi@ttsh.com.sg',
    phone: '64503333',
    serviceType: 'EAS (Emergency Ambulance Services)',
    tier: 'Critical',
    status: 'Confirmed',
    preferredDate: '13 Jun 2026',
    preferredTime: '11:00',
    pickup: 'Tan Tock Seng Hospital, Isolation Ward, 11 Jalan Tan Tock Seng, Singapore 308433',
    destination: 'National Centre for Infectious Diseases, 16 Jalan Tan Tock Seng, Singapore 308442',
    notes: 'COVID-19 positive patient. Full PPE required.',
  },
  {
    ref: 'EFAR-2026-00006',
    submitted: '12 Jun 2026, 10:00 PM',
    name: 'Chen Wei',
    org: 'Tan Tock Seng Hospital',
    email: 'chen.wei@ttsh.com.sg',
    phone: '64504444',
    serviceType: 'MTS (Medical Transfer Services)',
    tier: 'Advanced',
    status: 'Confirmed',
    preferredDate: '14 Jun 2026',
    preferredTime: '07:30',
    pickup: 'Changi Airport Terminal 3 Tarmac, Singapore 819663',
    destination: 'Jurong Island Medical Centre, Jurong Island, Singapore',
    notes: 'Repatriation case from inbound flight. Tarmac access required. Jurong Island destination.',
  },
  {
    ref: 'EFAR-2026-00009',
    submitted: '17 Jun 2026, 11:00 AM',
    name: 'James Wong',
    org: '',
    email: 'james.wong@personal.com',
    phone: '91112222',
    serviceType: 'MTS (Medical Transfer Services)',
    tier: 'Basic',
    status: 'Rejected',
    preferredDate: '20 Jun 2026',
    preferredTime: '10:00',
    pickup: 'Johor Bahru City Square, Malaysia',
    destination: 'Singapore General Hospital, Outram Road, Singapore 169608',
    notes: 'Pickup location is outside EFAR service area. EFAR covers Singapore territory only.',
  },
  {
    ref: 'EFAR-2026-00010',
    submitted: '19 Jun 2026, 05:30 PM',
    name: 'Nurul Huda',
    org: 'Parkway Pantai',
    email: 'nurul.h@parkwaypantai.com',
    phone: '67891011',
    serviceType: 'EAS (Emergency Ambulance Services)',
    tier: 'Basic',
    status: 'Rejected',
    preferredDate: '28 Jun 2026',
    preferredTime: '07:00',
    pickup: 'Mount Elizabeth Hospital, 3 Mount Elizabeth, Singapore 228510',
    destination: 'Raffles Hospital, 585 North Bridge Road, Singapore 188770',
    notes: 'Early morning transfer required before 0900.',
  },
];
